"""Build the standalone Insight Pages repository from local AI briefs."""
from __future__ import annotations

import argparse
import json
import shutil
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SOURCE = ROOT / "data" / "ai-briefs"
DEFAULT_TARGET = ROOT.parent / "firsthand-ai-insight"
INSIGHT_DOMAIN = "insight.ai.prov1dence.top"


@dataclass(frozen=True)
class SyncResult:
    latest_path: str
    copied_files: int


def _load_latest_path(source_dir: Path) -> str:
    index_path = source_dir / "index.json"
    payload = json.loads(index_path.read_text(encoding="utf-8"))
    briefs = payload.get("briefs") or []
    if not briefs or not isinstance(briefs[0], dict):
        raise ValueError(f"No briefs found in {index_path}")
    path = str(briefs[0].get("path") or "").strip()
    if not path:
        raise ValueError(f"Latest brief in {index_path} has no path")
    return path.lstrip("/")


def _write_root_index(target_dir: Path, latest_path: str) -> None:
    html = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="refresh" content="0; url={latest_path}">
<link rel="canonical" href="{latest_path}">
<title>Firsthand AI Insight</title>
<script>
location.replace("{latest_path}");
</script>
<style>
body {{
  margin: 0;
  min-height: 100vh;
  display: grid;
  place-items: center;
  font: 16px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  color: #1d1d1f;
  background: #f5f5f7;
}}
a {{ color: #0066cc; }}
</style>
</head>
<body>
<p>Opening the latest <a href="{latest_path}">Firsthand AI Insight</a>...</p>
</body>
</html>
"""
    (target_dir / "index.html").write_text(html, encoding="utf-8")


def _write_pages_workflow(target_dir: Path) -> None:
    workflow = """name: Deploy Insight

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: .

      - id: deployment
        uses: actions/deploy-pages@v5
"""
    path = target_dir / ".github" / "workflows" / "pages.yml"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(workflow, encoding="utf-8")


def _write_readme(target_dir: Path) -> None:
    readme = f"""# Firsthand AI Insight

Standalone GitHub Pages host for the AI interpretation briefs generated by
[`firsthand-ai-digest`](https://github.com/chr1sc2y/firsthand-ai-digest).

- Custom domain: `{INSIGHT_DOMAIN}`
- Root path: redirects to the latest English brief
- Brief files: `ai-briefs/*.html`

Do not edit generated brief files here by hand. Update the source brief in the
main digest repository and run `scripts/sync_insight_site.py`.
"""
    (target_dir / "README.md").write_text(readme, encoding="utf-8")


def sync(*, source_dir: Path = DEFAULT_SOURCE, target_dir: Path = DEFAULT_TARGET) -> SyncResult:
    source_dir = source_dir.expanduser().resolve()
    target_dir = target_dir.expanduser().resolve()
    if not source_dir.exists():
        raise FileNotFoundError(source_dir)

    latest_path = _load_latest_path(source_dir)
    target_dir.mkdir(parents=True, exist_ok=True)
    target_briefs = target_dir / "ai-briefs"
    if target_briefs.exists():
        shutil.rmtree(target_briefs)
    shutil.copytree(source_dir, target_briefs)
    copied_files = sum(1 for path in target_briefs.iterdir() if path.is_file())

    (target_dir / "CNAME").write_text(f"{INSIGHT_DOMAIN}\n", encoding="utf-8")
    _write_root_index(target_dir, latest_path)
    _write_pages_workflow(target_dir)
    _write_readme(target_dir)
    return SyncResult(latest_path=latest_path, copied_files=copied_files)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Sync local AI briefs into the standalone Insight Pages repo."
    )
    parser.add_argument("--source-dir", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--target-dir", type=Path, default=DEFAULT_TARGET)
    args = parser.parse_args(argv)

    result = sync(source_dir=args.source_dir, target_dir=args.target_dir)
    print(f"Synced {result.copied_files} brief file(s); latest={result.latest_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
