"""Build the standalone Insight Pages repository from local AI briefs."""
from __future__ import annotations

import argparse
import json
import shutil
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SOURCE = ROOT / "data" / "ai-briefs"
DEFAULT_TARGET = ROOT.parent / "firsthand-ai-insight"
INSIGHT_DOMAIN = "insight.ai.prov1dence.top"
PUBLIC_ARCHIVE_DIR = "archive"


@dataclass(frozen=True)
class SyncResult:
    latest_path: str
    copied_files: int


def _load_latest_path(source_dir: Path) -> str:
    index_path = source_dir / "index.json"
    payload = json.loads(index_path.read_text(encoding="utf-8"))
    briefs = payload.get("briefs") or []
    if not briefs or not isinstance(briefs[0], dict):
        raise ValueError(f"No briefs found in {index_path}")
    path = str(briefs[0].get("path") or "").strip()
    if not path:
        raise ValueError(f"Latest brief in {index_path} has no path")
    return path.lstrip("/")


def _write_root_index(source_dir: Path, target_dir: Path, latest_path: str) -> None:
    latest_source = source_dir / Path(latest_path).name
    html = latest_source.read_text(encoding="utf-8")
    # The root page displays the latest brief directly. A base URL keeps the
    # brief's relative language-switch links pointing at /archive/.
    if "<head>" in html and "<base " not in html:
        html = html.replace("<head>", f'<head>\n<base href="/{PUBLIC_ARCHIVE_DIR}/">', 1)
    (target_dir / "index.html").write_text(html, encoding="utf-8")


def _write_pages_workflow(target_dir: Path) -> None:
    workflow = """name: Deploy Insight

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4

      - name: Prepare Pages artifact
        run: |
          mkdir -p _site
          cp index.html CNAME _site/
          cp -R archive _site/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: _site

      - id: deployment
        uses: actions/deploy-pages@v5
"""
    path = target_dir / ".github" / "workflows" / "pages.yml"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(workflow, encoding="utf-8")


def _write_gitignore(target_dir: Path) -> None:
    gitignore = """# Pre-publish brief drafts from automation
staging/

# Local Pages build scratch
_site/

# OS / editor
.DS_Store
"""
    (target_dir / ".gitignore").write_text(gitignore, encoding="utf-8")


def _write_readme(target_dir: Path) -> None:
    readme = f"""# Firsthand AI Insight

Standalone GitHub Pages host for the AI interpretation briefs generated by
[`firsthand-ai-digest`](https://github.com/chr1sc2y/firsthand-ai-digest).

- Custom domain: `{INSIGHT_DOMAIN}`
- Root path: displays the latest English brief
- Brief files: `{PUBLIC_ARCHIVE_DIR}/*.html`

## Repository layout

| Path | Purpose |
|------|---------|
| `index.html` | Latest English brief (served at `/`) |
| `{PUBLIC_ARCHIVE_DIR}/` | Published brief HTML and `index.json` |
| `CNAME` | Custom domain for GitHub Pages |

Root keeps only the live Pages artifact. Source material and unpublished
drafts belong in the main digest repository, not here.

Do not edit generated brief files here by hand. Update the source brief in the
main digest repository and run `scripts/sync_insight_site.py`.
"""
    (target_dir / "README.md").write_text(readme, encoding="utf-8")


def sync(*, source_dir: Path = DEFAULT_SOURCE, target_dir: Path = DEFAULT_TARGET) -> SyncResult:
    source_dir = source_dir.expanduser().resolve()
    target_dir = target_dir.expanduser().resolve()
    if not source_dir.exists():
        raise FileNotFoundError(source_dir)

    latest_path = _load_latest_path(source_dir)
    target_dir.mkdir(parents=True, exist_ok=True)
    target_archive = target_dir / PUBLIC_ARCHIVE_DIR
    legacy_briefs = target_dir / "ai-briefs"
    if target_archive.exists():
        shutil.rmtree(target_archive)
    if legacy_briefs.exists():
        shutil.rmtree(legacy_briefs)
    shutil.copytree(source_dir, target_archive)
    copied_files = sum(1 for path in target_archive.iterdir() if path.is_file())

    (target_dir / "CNAME").write_text(f"{INSIGHT_DOMAIN}\n", encoding="utf-8")
    _write_root_index(source_dir, target_dir, latest_path)
    _write_pages_workflow(target_dir)
    _write_gitignore(target_dir)
    _write_readme(target_dir)
    return SyncResult(latest_path=latest_path, copied_files=copied_files)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Sync local AI briefs into the standalone Insight Pages repo."
    )
    parser.add_argument("--source-dir", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--target-dir", type=Path, default=DEFAULT_TARGET)
    args = parser.parse_args(argv)

    result = sync(source_dir=args.source_dir, target_dir=args.target_dir)
    print(f"Synced {result.copied_files} brief file(s); latest={result.latest_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
